services:
  postgres_database:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    container_name: postgres
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - hms-app

  react_client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    command: npm run dev
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hms-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django_backend

  django_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - hms-app
    depends_on:
      - postgres_database

volumes:
  postgres_data:

networks:
  hms-app:
    driver: bridge
