services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    container_name: hms_database

    env_file:
      - ./backend/.env

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hms_frontend
    restart: always

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules 

    environment:
      - CHOKIDAR_USEPOLLING=true

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hms_backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    depends_on:
      - db
      
volumes:
  postgres_data:
