version: "3.8"

services:
  postgres_database:
    image: postgres:14-alpine
    expose:
      - "5432"
    container_name: postgres
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - hms-app

  react_client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    command: npm run dev
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hms-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django_backend

  django_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - static_data:/app/static
    networks:
      - hms-app
    depends_on:
      - postgres_database
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
      - static_data:/app/static
    networks:
      - hms-app
    depends_on:
      - django_backend
      - react_client

volumes:
  postgres_data:
  static_data:

networks:
  hms-app:
    driver: bridge
