services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    container_name: hms_database

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hms_frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    stdin_open: true
    tty: true

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hms_backend

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app/backend

    depends_on:
      - db
